### ISSUE TITLE
XML Support seems laborious to me

### ISSUE THREAD

**Issue by git-emil** [jannisborn/pyacddb#12]
This is use full to handle master list of categories, keywords and collections, or a small subset of the catalogued images. Showing up the "Image hive" and select all images to create a complete XML file is far to slow, if not impossible. I'd prefer access to the database itself.

E.g. A master list of keywords is nice to find typos. But it doesn't allow to correct the typos assigned to the catalogued items. 
Work around: 
- Find typos in master list of keywords
- Search for all items with assigned typos in ACDSee
- Select the found images and export to XML file
- correct the typos in the XML file
- import the XML file in ACDSee

Quite cumbersome. This also doesn't allow to eliminate the typo from the master list! [sigh]

**Comment by jannisborn** [comment]
Hi @git-emil,
Thanks for your interest in using the package. It is in very early development, this is why I havent even pushed it to PyPI or anything. I wrote the code in the `pyacddb` folder solely to process the XML file produced and exported by ACDSeePro and convert them to another format (e.g., `csv`). 


Not sure I fully get your feature request. You want to have a way to correct typos in the keywords you assigned to ACDSee images? Why would you want to do this __outside__ ACDSee via this package?

Happy to support but not sure I understand the issue fully.

**Comment by git-emil** [comment]
Afaik you can only export XML data from ACDSee database for files selected in manage mode.
I have >360,000 catalogued items and showing them all in manage mode with the "special object" "image hive" takes lots of time. But then I also need to select them all (CTRL-A). This never ever worked for me, it will surely crash ACDSee. 

If I would need a CSV file with meta data of my images I'd use exiftool. Still a long run but doable.
To keep the CSV file up to date, an export would also need to be done regularly.

At the moment I a go a rocky shortcut:
- I embed all meta data within ACDSee.
- I run a py script in background to copy certain meta data into the alternate data streams of the files (97% are XMP-files)
- I use Everything (https://www.voidtools.com/forum/viewtopic.php?t=9787) to search for meta data

Everything is amazingly fast: It returns results while typing the search phrase, even for 3 mio catalogued items! It's downside is the missing support for XMP and IPTC data.

I'd prefer direct access to the ACDSee database from outside, but afaik even then ACDSee SDK (https://www.acdsee.io) doesn't offer this.

BTW. The typos are just are sample usage. There's many more.

**Comment by jannisborn** [comment]
Interesting. @UserMicha has observed the same problem when trying to export large amounts of data from ACDSee. He knows much better than me the challenges when doing this.

Currently the intention of this library is only to read XML files that were extracted before (manually, I guess) from ACDSee. I was not planning to build a direct access to ACDSee. As you say, this should be done by an SDK IMHO...

**Comment by jannisborn** [comment]
Hi @git-emil I will close this issue because I still do not really understand which piece of code would resolve your issue.
If you could sketch the code or pseudocode that you would, I would be happy to have a look
