### ISSUE TITLE
Intervall für Ausgabe einer Serie von vielen Bildern

### ISSUE THREAD

**Issue by UserMicha** [jannisborn/pyacddb#5]
Hi Jannis, 
ich würde es praktisch finden, wenn bei der Ausgabe von mehr als 10 Bildern nach dem jeweils 10. Bild eine "more?"-Abfrage kommen würde. Denn vielleicht ist das gesuchte schon da, und die anderen brauchen erst gar nicht gesendet werden.

**Comment by jannisborn** [comment]
Das geht einfach, hab ich ja bei dem Münzbot schon gelöst gehabt!

**Comment by UserMicha** [comment]
Danke, funktioniert prima!
