### ISSUE TITLE
Problem mit dem "Bitte mehr" Button

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/pyacddb#7]
der button funktioniert grundsätzlich, allerdings wenn man den Button ignoriert, und eine neue Texteingabe macht und dann den Knopf drückt, dann werden immer die gleichen Bilder gezeigt (vermutlich diejenigen die chronologisch in der gesamten DB ganz oben stehen)

**Comment by jannisborn** [comment]
@Usermicha kannst du das bestätigen?

**Comment by UserMicha** [comment]
Nein, habe ich noch nicht reproduzieren können. beschreib doch mal ganz genau deinen Ablauf.

**Comment by jannisborn** [comment]
Closed via #9
